config/routes.rb
Rails.application.routes.draw do

  resources :destinatarios do
  #para autocompletar o fone do cliente na venda
  get :autocomplete_destinatario_celular, :on => :collection
  end
  #abrindo um form modal para cadastrar novos clientes na venda delivery
  get 'desk_orders/new_cliente' => 'desk_orders#new_cliente', :as => :new_cliente

  resources :configs
  resources :form_payments
  #Para o action cable
  mount ActionCable.server => '/cable'

  #ROTAS DO APLICATIVO
  #verifica se a mesa esta liberada
  post 'check_mesa', to: 'desk_orders#check_mesa'
  #lista as categorias dos produtos no cardápio
  get 'list_categories', to: 'desk_orders#list_categories'
  #lista os produtos de acordo com a categoria selecionada
  post 'list_products', to: 'desk_orders#list_products'
  #adiciona o produto selecionado na mesa que está aberta
  post 'add_product', to: 'desk_orders#add_product'
  #exibe tudo o que já foi consumido
  post 'check_order', to: 'desk_orders#check_order'
  #solicita o fechamento da mesa
  post 'close_order', to: 'desk_orders#close_order'
  #exclui o item selecionado se ainda não mudou o status
  post 'delete_item', to: 'desk_orders#delete_item'
  #----------------------------------------------------

  #abrindo um form modal para informar os tributos do pruduto na invoice
  get 'items/editar_tributo' => 'items#editar_tributo', :as => :editar_tributo

  resources :payments
  resources :loginfos
  resources :suppliers do
  #para autocompletar o nome do produto
  get :autocomplete_supplier_name, :on => :collection
  end
  resources :receipts
  resources :qrpoints
  resources :items
  resources :desk_orders do
    member do
     post 'baixar'
     post 'nfce'
     get 'gerar_nfce'

  end
    resources :items do
    end
  end
    resources :items
    post 'barcode', to: 'desk_orders#barcode'
  #para cancelar a nfe
  get 'cancelar_nfe', to: 'desk_orders#cancelar_nfe'
  #para efetivar o cancelamento da nfe
  post 'cancel_nfe', to: 'desk_orders#cancel_nfe'

  resources :products do
    #para autocompletar o nome do produto
   get :autocomplete_product_name, :on => :collection
   #para autocompletar com o codigo de barras lidos
   get :autocomplete_product_barcode, :on => :collection
  end
  #rota para consultar produto selecionado no combobox na Ordem de serviço
  get 'consulta_prod', to: 'products#consulta_prod'
  get 'consulta_prod_barcode', to: 'products#consulta_prod_barcode'


  resources :categories
  get 'pages/login'

  resources :users
  root 'pages#login'

  get 'sessions/new'
  #rotas para o login
  get 'expired', to: 'sessions#expired_date'
  get 'pages/index'
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  #---------------------------------------------
  get 'dashboard', to: 'pages#dashboard'
  #para carregar a view informando que não pode excluir cadastro com relacionamento em outra table
  get 'message_error_relation_tables', to: 'pages#message_error_relation_tables'
end

app/models/destinatario.rb
class Destinatario < ApplicationRecord
  attr_accessor :type_save
  belongs_to :desk_order, optional: true
  validates :nome, :cep, :endereco, :numero, :bairro, :cidade, :celular, presence: true
  validates :celular, uniqueness: true
end

app/controllers/destinatarios_controller.rb
class DestinatariosController < ApplicationController
  before_action :set_destinatario, only: [:show, :edit, :update, :destroy]

  #para autocompletar o fone do cliente na venda
  autocomplete :destinatario, :celular, :full => true

  def index
    @destinatarios = Destinatario.all
  end

  # GET /destinatarios/1
  # GET /destinatarios/1.json
  def show
  end

  # GET /destinatarios/new
  def new
    @destinatario = Destinatario.new
  end

  # GET /destinatarios/1/edit
  def edit
  end

  # POST /destinatarios
  # POST /destinatarios.json
  def create
    @destinatario = Destinatario.new(destinatario_params)

    respond_to do |format|
      if @destinatario.save
        #inserindo no log de atividades
        log = Loginfo.new(params[:loginfo])
        log.employee = current_user.name
        log.task = 'Cadastrou novo cliente - Nome: ' + destinatario_params[:nome_destinatario].to_s
        log.save!

        format.html { }
        format.json { render :show, status: :created, location: @destinatario }
        sweetalert_success('Cliente criado com sucesso.', 'Aviso')

        #verifica se o produto esta sendo criado lá na geração da venda
        if destinatario_params[:type_save].present?
          redirect_to new_desk_order_path
        else
        redirect_to @destinatario
        end

      else
        format.html { render :new }
        format.json { render json: @destinatario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinatarios/1
  # PATCH/PUT /destinatarios/1.json
  def update
    respond_to do |format|
      if @destinatario.update(destinatario_params)
        format.html { redirect_to @destinatario, notice: 'Destinatario was successfully updated.' }
        format.json { render :show, status: :ok, location: @destinatario }
      else
        format.html { render :edit }
        format.json { render json: @destinatario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinatarios/1
  # DELETE /destinatarios/1.json
  def destroy
    @destinatario.destroy
    respond_to do |format|
      format.html { redirect_to destinatarios_url, notice: 'Destinatario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destinatario
      @destinatario = Destinatario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destinatario_params
      params.require(:destinatario).permit(:nome, :endereco, :numero, :bairro, :complemento, :cidade, :celular, :email, :obs, :cep, :type_save)
    end
end

app/helpers/destinatarios_helper.rb
module DestinatariosHelper
end

app/views/destinatarios/_form.html.erb
<!-- PARA CARREGAR O ENDEREÇO COM BASE NO CEP -->
    <!-- Adicionando JQuery -->
    <script>
        $(document).ready(function() {

            function limpa_formulário_cep() {
                // Limpa valores do formulário de cep.
                $("#rua").val("");
                $("#bairro").val("");
                $("#cidade").val("");
                $("#uf").val("");
                $("#ibge").val("");
            }

            //Quando o campo cep perde o foco.
            $("#cep").blur(function() {

                //Nova variável "cep" somente com dígitos.
                var cep = $(this).val().replace(/\D/g, '');

                //Verifica se campo cep possui valor informado.
                if (cep != "") {

                    //Expressão regular para validar o CEP.
                    var validacep = /^[0-9]{8}$/;

                    //Valida o formato do CEP.
                    if(validacep.test(cep)) {

                        //Preenche os campos com "..." enquanto consulta webservice.
                        $("#rua").val("...")
                        $("#bairro").val("...")
                        $("#cidade").val("...")
                        $("#uf").val("...")
                        $("#ibge").val("...")

                        //Consulta o webservice viacep.com.br/
                        $.getJSON("//viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                            if (!("erro" in dados)) {
                                //Atualiza os campos com os valores da consulta.
                                $("#rua").val(dados.logradouro);
                                $("#bairro").val(dados.bairro);
                                $("#cidade").val(dados.localidade);
                                $("#uf").val(dados.uf);
                                $("#ibge").val(dados.ibge);
                            } //end if.
                            else {
                                //CEP pesquisado não foi encontrado.
                                limpa_formulário_cep();
                                alert("CEP não encontrado.");
                            }
                        });
                    } //end if.
                    else {
                        //cep é inválido.
                        limpa_formulário_cep();
                        alert("Formato de CEP inválido.");
                    }
                } //end if.
                else {
                    //cep sem valor, limpa formulário.
                    limpa_formulário_cep();
                }
            });
        });

    </script>

<%= form_for @destinatario, :html => { :class => "form-horizontal destinatario" } do |f| %>

  <% if @destinatario.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@destinatario.errors.count, "erro(s)") %> Existe inconsistência nos dados:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @destinatario.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
      <%= f.text_field :nome, :class => 'form-control', autofocus: true %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :cep, :class => 'control-label col-lg-2' %>
    <div class="col-lg-1">
      <%= f.text_field :cep, :class => 'form-control', id: 'cep' %>
    </div>
    <%=f.error_span(:cep) %>
  </div>
  <div class="form-group">
    <%= f.label 'name', 'Endereço', :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :endereco, :class => 'form-control', id: 'rua' %>
    </div>
    <%=f.error_span(:endereco) %>
  </div>
  <div class="form-group">
    <%= f.label 'name', 'Nº', :class => 'control-label col-lg-2' %>
    <div class="col-lg-1">
      <%= f.text_field :numero, :class => 'form-control' %>
    </div>
    <%=f.error_span(:numero) %>
  </div>
  <div class="form-group">
    <%= f.label :complemento, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :complemento, :class => 'form-control' %>
    </div>
    <%=f.error_span(:complemento) %>
  </div>
  <div class="form-group">
    <%= f.label :bairro, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :bairro, :class => 'form-control', id: 'bairro' %>
    </div>
    <%=f.error_span(:bairro) %>
  </div>
  <div class="form-group">
    <%= f.label :cidade, :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.text_field :cidade, :class => 'form-control', id: 'cidade' %>
    </div>
    <%=f.error_span(:cidade) %>
  </div>
  <div class="form-group">
    <%= f.label :celular, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :celular, :class => 'form-control', id: 'celphone' %>
    </div>
    <%=f.error_span(:celular) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :obs, :class => 'control-label col-lg-2' %>
    <div class="col-lg-5">
      <%= f.text_area :obs, :class => 'form-control' %>
    </div>
    <%=f.error_span(:obs) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                destinatarios_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/destinatarios/edit.html.erb
<%- model_class = Destinatario -%>
<div class="page-header">
  <h1>Editar cliente</h1>
</div>
<%= render :partial => 'form' %>

app/views/destinatarios/index.html.erb
<%- model_class = Destinatario -%>
<div class="page-header">
  <h1>Cadastro de Clientes <%=image_tag('client.png') %></h1>
  <%= link_to t('.new', :default => t("helpers.links.new")), new_destinatario_path, :class => 'btn btn-primary' %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cep</th>
      <th>Endereço</th>
      <th>Nº</th>
      <th>Bairro</th>
      <th>Complemento</th>
      <th>Cidade</th>
      <th>Celular</th>
      <th>Email</th>
      <th>Criado em</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @destinatarios.each do |destinatario| %>
      <tr>
        <td><%= link_to destinatario.nome, destinatario_path(destinatario) %></td>
        <td><%= destinatario.cep %></td>
        <td><%= destinatario.endereco %></td>
        <td><%= destinatario.numero %></td>
        <td><%= destinatario.bairro %></td>
        <td><%= destinatario.complemento %></td>
        <td><%= destinatario.cidade %></td>
        <td><%= destinatario.celular %></td>
        <td><%= destinatario.email %></td>
        <td><%= destinatario.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      destinatario_path(destinatario), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_destinatario_path(destinatario), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      destinatario_path(destinatario),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/destinatarios/new.html.erb
<%- model_class = Destinatario -%>
<div class="page-header">
  <h1>Novo cliente</h1>
</div>
<%= render :partial => 'form' %>

app/views/destinatarios/show.html.erb
<%- model_class = Destinatario -%>
<div class="page-header">
  <h1>Cliente</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @destinatario.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:endereco) %>:</strong></dt>
  <dd><%= @destinatario.endereco %></dd>
  <dt><strong>Nº:</strong></dt>
  <dd><%= @destinatario.numero %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bairro) %>:</strong></dt>
  <dd><%= @destinatario.bairro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:complemento) %>:</strong></dt>
  <dd><%= @destinatario.complemento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cidade) %>:</strong></dt>
  <dd><%= @destinatario.cidade %></dd>
  <dt><strong><%= model_class.human_attribute_name(:celular) %>:</strong></dt>
  <dd><%= @destinatario.celular %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @destinatario.email %></dd>
  <% if @destinatario.obs.present? %>
  <dt><strong><%= model_class.human_attribute_name(:obs) %>:</strong></dt>
  <dd><%= @destinatario.obs %></dd>
  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              destinatarios_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_destinatario_path(@destinatario), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              destinatario_path(@destinatario),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>