config/routes.rb
Rails.application.routes.draw do

  resources :destinatarios do
  #para autocompletar o fone do cliente na venda
  get :autocomplete_destinatario_celular, :on => :collection
  end
  #abrindo um form modal para cadastrar novos clientes na venda delivery
  get 'desk_orders/new_cliente' => 'desk_orders#new_cliente', :as => :new_cliente

  resources :configs
  resources :form_payments
  #Para o action cable
  mount ActionCable.server => '/cable'

  #ROTAS DO APLICATIVO
  #verifica se a mesa esta liberada
  post 'check_mesa', to: 'desk_orders#check_mesa'
  #lista as categorias dos produtos no cardápio
  get 'list_categories', to: 'desk_orders#list_categories'
  #lista os produtos de acordo com a categoria selecionada
  post 'list_products', to: 'desk_orders#list_products'
  #adiciona o produto selecionado na mesa que está aberta
  post 'add_product', to: 'desk_orders#add_product'
  #exibe tudo o que já foi consumido
  post 'check_order', to: 'desk_orders#check_order'
  #solicita o fechamento da mesa
  post 'close_order', to: 'desk_orders#close_order'
  #exclui o item selecionado se ainda não mudou o status
  post 'delete_item', to: 'desk_orders#delete_item'
  #----------------------------------------------------

  #abrindo um form modal para informar os tributos do pruduto na invoice
  get 'items/editar_tributo' => 'items#editar_tributo', :as => :editar_tributo

  resources :payments
  resources :loginfos
  resources :suppliers do
  #para autocompletar o nome do produto
  get :autocomplete_supplier_name, :on => :collection
  end
  resources :receipts
  resources :qrpoints
  resources :items
  resources :desk_orders do
    member do
     post 'baixar'
     post 'nfce'
     get 'gerar_nfce'

  end
    resources :items do
    end
  end
    resources :items
    post 'barcode', to: 'desk_orders#barcode'
  #para cancelar a nfe
  get 'cancelar_nfe', to: 'desk_orders#cancelar_nfe'
  #para efetivar o cancelamento da nfe
  post 'cancel_nfe', to: 'desk_orders#cancel_nfe'

  resources :products do
    #para autocompletar o nome do produto
   get :autocomplete_product_name, :on => :collection
   #para autocompletar com o codigo de barras lidos
   get :autocomplete_product_barcode, :on => :collection
  end
  #rota para consultar produto selecionado no combobox na Ordem de serviço
  get 'consulta_prod', to: 'products#consulta_prod'
  get 'consulta_prod_barcode', to: 'products#consulta_prod_barcode'


  resources :categories
  get 'pages/login'

  resources :users
  root 'pages#login'

  get 'sessions/new'
  #rotas para o login
  get 'expired', to: 'sessions#expired_date'
  get 'pages/index'
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  #---------------------------------------------
  get 'dashboard', to: 'pages#dashboard'
  #para carregar a view informando que não pode excluir cadastro com relacionamento em outra table
  get 'message_error_relation_tables', to: 'pages#message_error_relation_tables'
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :supplier
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]
  before_action :show_supplier_name, only: [:new, :edit, :update, :create, :index, :report_payment]
  before_action :must_login

  def index
@payments = Payment.includes(:supplier).where(due_date: Date.today).order(:due_date)
    @total_payments = Payment.where(due_date: Date.today).sum(:value_doc)

    if params[:date1].present? && params[:date2].present? && params[:tipo_consulta].blank? && params[:fornecedor].blank?
       @payments = Payment.where("due_date BETWEEN ? AND ?", params[:date1], params[:date2]).order(:due_date)
       @total_payments = Payment.where("due_date BETWEEN ? AND ?", params[:date1], params[:date2]).sum(:value_doc)

     elsif params[:date1].present? && params[:date2].present? && params[:tipo_consulta].blank? && params[:fornecedor].present?
       @payments = Payment.where(supplier_id: params[:fornecedor]).where("due_date BETWEEN ? AND ?", params[:date1], params[:date2]).order(:due_date)
       @total_payments = Payment.where(supplier_id: params[:fornecedor]).where("due_date BETWEEN ? AND ?", params[:date1], params[:date2]).sum(:value_doc)

    elsif params[:date1].present? && params[:date2].present? && params[:tipo_consulta].present? && params[:fornecedor].blank?
       @payments = Payment.where("due_date BETWEEN ? AND ?", params[:date1], params[:date2]).where(status: params[:tipo_consulta]).order(:due_date)
       @total_payments = Payment.where("due_date BETWEEN ? AND ?", params[:date1], params[:date2]).where(status: params[:tipo_consulta]).sum(:value_doc)

    elsif params[:date1].present? && params[:date2].present? && params[:tipo_consulta].present? && params[:fornecedor].present?
       @payments = Payment.where("payment_date BETWEEN ? AND ?", params[:date1], params[:date2]).where(supplier_id: params[:fornecedor]).where(status: params[:tipo_consulta]).order(:due_date)
       @total_payments = Payment.where("payment_date BETWEEN ? AND ?", params[:date1], params[:date2]).where(supplier_id: params[:fornecedor]).where(status: params[:tipo_consulta]).sum(:value_doc)
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)
    @qnt_parcela = payment_params[:installments].to_i

    if payment_params[:type_doc].blank? || payment_params[:supplier_id].blank? || payment_params[:description].blank? || payment_params[:due_date].blank? || payment_params[:installments].blank? || payment_params[:value_doc].blank?
        sweetalert_warning('Os dados precisam ser informados primeiro!', 'Atenção!', useRejections: false)
      redirect_to new_payment_path and return
    end

    #verifica se foi informada a forma de pagamento na baixa
    if payment_params[:status] == 'Paga' && payment_params[:form_payment].blank?
        sweetalert_warning('Selecione uma forma de pagamento!', 'Atenção!', useRejections: false)
      redirect_to new_payment_path and return
    end

    #se informou a data da baixa e não alterou para PAGA o status
    if payment_params[:payment_date].present? && payment_params[:status] == 'Á Pagar'
    sweetalert_warning('Altere o Status para PAGA, já que você informou a data de pagamento!', 'Atenção!', useRejections: false)
      redirect_to new_payment_path and return
    end

    #se alterou para PAGA o status e não informou a data do pagamento
    if payment_params[:status] == 'Paga' && payment_params[:payment_date].blank?
        sweetalert_warning('Informe a data de pagamento, já que você alterou o status para PAGA!', 'Atenção!', useRejections: false)
      redirect_to new_payment_path and return
    end


    #se for somente uma parcela ele só salva uma vez
    if @qnt_parcela == 1

            respond_to do |format|
              if @payment.save
        #inserindo no log de atividades
        log = Loginfo.new(params[:loginfo])
        log.employee = current_user.name
        log.task = 'Cadastrou nova conta á pagar - Nº doc: ' + payment_params[:doc_number].to_s
        log.save!
                format.html { }
                format.json { render :show, status: :created, location: @payment }
                sweetalert_success('Pagamento cadastrado com sucesso!', 'Sucesso!', useRejections: false)
                redirect_to @payment
              else
                format.html { render :new }
                format.json { render json: @payment.errors, status: :unprocessable_entity }
              end
            end
     else
          #se tiver mais de uma parcela ele lança a quantidade de vezes no sistema
          if @qnt_parcela > 1
            @valor_total = payment_params[:value_doc].to_f
            @resultado = @valor_total / @qnt_parcela
            @resultado = (@resultado).round(2)
            @data_vencto = payment_params[:due_date]
          end

        while @qnt_parcela > 0
         @conta_parc = @conta_parc.to_i + 1
         @data_vencto = @data_vencto.to_date + 1.month
         @payment.description = payment_params[:description] + ' Parc. ' + @conta_parc.to_s
         @payment.due_date = @data_vencto
         @payment.payment_date = Date.today
         @payment.value_doc = @resultado

            if @payment.save
              #só vai fazer o redirect quando finalizar
            else
              format.html { render :new }
              format.json { render json: @payment.errors, status: :unprocessable_entity }
            end
         @qnt_parcela = @qnt_parcela - 1
         @payment = Payment.new(payment_params)
        end
      redirect_to payments_path
      sweetalert_success('Parcelamento realizado com sucesso!', 'Sucesso!', useRejections: false)
     end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    #verifica se foi informada a forma de pagamento na baixa
    if payment_params[:payment_date].present? && payment_params[:form_payment].blank?
        sweetalert_warning('Selecione uma forma de Pagamento!', 'Atenção!', useRejections: false)
      redirect_to edit_payment_path(@payment) and return
    end

    #se informou a data da baixa e não alterou para PAGA o status
    if payment_params[:payment_date].present? && payment_params[:status] == 'Á Pagar'
        sweetalert_warning('Altere o Status para PAGA, já que você informou a data de pagamento!', 'Atenção!', useRejections: false)
      redirect_to edit_payment_path(@payment) and return
    end

    #se alterou para PAGA o status e não informou a data do pagamento
    if payment_params[:status] == 'Paga' && payment_params[:payment_date].blank?
        sweetalert_warning('Informe a data de pagamento, já que você alerou o status para PAGA!', 'Atenção!', useRejections: false)
      redirect_to edit_payment_path(@payment) and return
    end

    respond_to do |format|
      if @payment.update(payment_params)
        #inserindo no log de atividades
        log = Loginfo.new(params[:loginfo])
        log.employee = current_user.name
        log.task = 'Atualizou conta á pagar - Nº doc ' + payment_params[:doc_number].to_s
        log.save!
        format.html { }
        format.json { render :show, status: :ok, location: @payment }
          sweetalert_success('Dados atualizados com sucesso.', 'Sucesso!', useRejections: false)
        redirect_to @payment
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    #inserindo no log de atividades
        log = Loginfo.new(params[:loginfo])
        log.employee = current_user.name
        log.task = 'Excluiu conta á pagar - Nº doc ' + @payment.doc_number.to_s
        log.save!
        sweetalert_success('Dados excluidos com sucesso.', 'Sucesso!', useRejections: false)
      redirect_to payments_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:doc_number, :description, :due_date, :payment_date, :installments, :value_doc, :type_doc, :form_payment, :status, :supplier_id,:purchase_id)
    end
    #mostra o nome do fornecedor
    def show_supplier_name
      @suppliers = Supplier.order(:name)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<script>
	//escrever em caixa alta
	$('#doc_number').ready(function() {

	jQuery('#doc_number').keyup(function() {
		$(this).val($(this).val().toUpperCase());
	});
	});
</script>
<%= form_for @payment, :html => { :class => "form-horizontal payment" } do |f| %>

  <% if @payment.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @payment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Nº doc', :class => 'control-label col-lg-2' %>
    <div class="col-lg-1">
      <%= f.text_field :doc_number, :class => 'form-control', id: 'doc_number' %>
    </div>
    <%=f.error_span(:doc_number) %>
  </div>
    <div class="form-group">
    <%= f.label "tipo doc", :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
      <%= f.select(:type_doc, options_for_select([["Boleto"], ["Carnê"],["Promissória"],["Outros"]], @payment.type_doc), {include_blank: 'Selecione'}, :class => 'form-control') %>
    </div>
    <%=f.error_span(:doc_number) %>
  </div>
    <div class="form-group">
    <%= f.label 'fornecedor', :class => 'control-label col-lg-2' %>
    <div class="col-lg-5">
   <% if @payment.supplier_id.present? %>
   <%= f.autocomplete_field :supplier_id, autocomplete_supplier_name_suppliers_path, :id_element => '#pega_id', :value => @payment.supplier.name, :class => 'form-control',placeholder: 'Digite o nome:', id: 'nome' %>
   <% else %>
  <%= f.autocomplete_field :supplier_id, autocomplete_supplier_name_suppliers_path, :id_element => '#pega_id', :class => 'form-control',placeholder: 'Digite o nome:', id: 'nome' %>
  <% end %>
   <%= f.hidden_field :supplier_id, :id => "pega_id" %>
    </div>
    <%=f.error_span(:supplier_id) %>
  </div>
  <div class="form-group">
    <%= f.label 'descrição', :class => 'control-label col-lg-2' %>
    <div class="col-lg-5">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label 'data vencimento', :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.date_field :due_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:due_date) %>
  </div>
  <div class="form-group">
    <%= f.label 'data pagamento', :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.date_field :payment_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:payment_date) %>
  </div>
<div class="form-group">
    <%= f.label 'parcelas', :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.select(:installments, options_for_select([["1"], ["2"],["3"],["4"], ["5"],["6"],["7"], ["8"],["9"],["10"], ["11"],["12"]], @payment.installments), {include_blank: 'Selecione'},:class => 'form-control') %>
    </div>
    <%=f.error_span(:installments) %>
  </div>
  <div class="form-group">
    <%= f.label 'Valor R$', :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <% if @payment.value_doc.present? %>
      <%= f.text_field :value_doc, :class => 'form-control', id: 'real', value: "%.2f" % f.object.value_doc %>
      <% else %>
      <%= f.text_field :value_doc, :class => 'form-control', id: 'real' %>
      <% end %>
    </div>
    <%=f.error_span(:value_doc) %>
  </div>

 <div class="form-group">
    <%= f.label 'forma pagto', :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.select(:form_payment, options_for_select([["Cheque"], ["Crédito"], ["Débito"], ["Dinheiro"]], @payment.form_payment), {include_blank: 'Selecione'}, :class => 'form-control') %>
    </div>
    <%=f.error_span(:form_payment) %>
  </div>
<div class="form-group">
    <%= f.label "status", :class => 'control-label col-lg-2' %>
    <div class="col-lg-2">
      <%= f.select(:status, options_for_select([["Á pagar"], ["Paga"]], @payment.status), {include_blank: 'Selecione'}, :class => 'form-control') %>
    </div>
    <%=f.error_span(:status) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit 'Salvar', data: { disable_with: "Processando..." }, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                payments_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/payments/edit.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1>Editar</h1>
</div>
<%= render :partial => 'form' %>

app/views/payments/index.html.erb
<style type="text/css">
	@media print {
    #printbtn {
        display :  none;
    }

    @media print {
  a[href]:after {
    content: none !important;
  }
}
}

#printOnly {
   display : none;
}

@media print {
    #printOnly {
       display : block;
    }
}
</style>

<%- model_class = Payment -%>
<div class="page-header">
  <h1>Contas á Pagar <%= image_tag('payments.png') %></h1>
  <div id="printOnly">
    Gerado em: <%= Time.now.strftime("%d/%m/%Y %H:%M") %><br />
  </div>
<%= form_tag(payments_path, method: :get) do %>
<div class="form-group">
		<div class="row">
			  <div class="col-lg-3">
			  <%= select_tag(:tipo_consulta, options_for_select([['Á pagar'],['Paga']]), include_blank: 'Selecione:', class: 'form-control', id: 'printbtn')%>
			</div>
			</div>
		<div class="form-group" id="printbtn">
		<div class="row">
			  <div class="col-lg-2">
		<%= select_tag(:fornecedor, options_from_collection_for_select(@suppliers, "id", "name", params[:fornecedor]), include_blank: 'Selecione o Fornecedor', class: 'form-control', id: 'printbtn') %>
		<%= date_field_tag(:date1,params[:date1], placeholder: 'data inicial', class: 'form-control') %>
		<%= date_field_tag(:date2,params[:date2], placeholder: 'data final', class: 'form-control') %>
		</div>
		</div>
		<br />
		<%= submit_tag "Consultar", class: 'btn btn-success' %>
<% end %>
<%= link_to "Novo", new_payment_path, :class => 'btn btn-primary' %>
<button type="button" id ="printbtn" class="btn btn-success", onclick ="window.print();return false;">Imprimir</button>
</div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name('Nº docto') %></th>
      <th><%= model_class.human_attribute_name('fornecedor') %></th>
      <th><%= model_class.human_attribute_name('Tipo docto') %></th>
      <th><%= model_class.human_attribute_name('descrição') %></th>
      <th><%= model_class.human_attribute_name('Vencto') %></th>
      <th><%= model_class.human_attribute_name('Pagto') %></th>
      <th><%= model_class.human_attribute_name('Nº parc') %></th>
      <th><%= model_class.human_attribute_name('Valor R$') %></th>
      <th><%= model_class.human_attribute_name('Status') %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= link_to payment.doc_number, payment_path(payment) %></td>
        <td><%= payment.supplier.name %></td>
        <td><%= payment.type_doc %></td>
        <td><%= payment.description %></td>
        <td><%= payment.due_date.strftime('%d/%m/%Y') %></td>
        <td><%= payment.payment_date.strftime('%d/%m/%Y') %></td>
        <td><%= payment.installments %></td>
        <td>R$ <%= number_with_precision(payment.value_doc, precision: 2) %></td>
        <td><%= payment.status %></td>
        <td>
          <%= link_to 'editar / baixar',
                      edit_payment_path(payment), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      payment_path(payment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @total_payments != 0 %>
<h3 align="right">Total R$: <b><%= number_with_precision(@total_payments, precision: 2) %></b></h3>
<% end %>

app/views/payments/new.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1>Nova conta á Pagar</h1>
</div>
<%= render :partial => 'form' %>

app/views/payments/report_payment.html.erb
<!-- CSS PARA REMOVER O BOTÃO IMPRIMIR NA VIEW DE IMPRESSÃO -->
  <style type="text/css">
	@media print {
    #printbtn {
        display :  none;
    }
}
</style>

<div class="container-fluid">

<%- model_class = Payment -%>
<br />
<h2>Relatório geral de Contas á Pagar <%= image_tag "logo.png" %></h2>
  
  Periodo: <%= @datainicial %> até <%=@datafinal %>
  
  
  <%= form_tag(report_payment_path, method: :get) do %>
			
  <div class="form-group">			  
		<div class="row">
			  <div class="col-lg-3">		
		<%= select_tag(:supplier, options_from_collection_for_select(@suppliers, "id", "name"), include_blank: 'Selecione o fornecedor:', class: 'form-control', id: 'printbtn') %>			  	
		</div>
		</div>	
  
	<div class="form-group">
		<div class="row">
			  <div class="col-lg-3">
			  <%= select_tag(:tipo_consulta, options_for_select([['Á PAGAR', 'Á PAGAR'], ['PAGAS', 'PAGA']]), include_blank: 'Selecione:', class: 'form-control', id: 'printbtn')%>
			</div>
			</div>
		<div class="form-group">			  
		<div class="row">
			  <div class="col-lg-2">	  
		<%= date_field_tag(:date1, params[:date1], placeholder: 'data inicial', class: 'form-control', id: 'printbtn') %>
		<%= date_field_tag(:date2, params[:date2], placeholder: 'data final', class: 'form-control', id: 'printbtn') %>	
		</div>
		</div>
		<br />	
		<%= submit_tag "Consultar", class: 'btn btn-success', id: 'printbtn' %>
<% end %>

	<button type="button" id ="printbtn" class="btn btn-success", onclick ="window.print();return false;">Imprimir</button>
 
 
 <h3><font color="red"><%= flash_messages %></font></h3>

<table class="table table-striped">
  <thead>
    <tr>
      
      <th><%= model_class.human_attribute_name('Nº docto') %></th>
      <th><%= model_class.human_attribute_name('tipo') %></th>
      <th><%= model_class.human_attribute_name('fornecedor') %></th>
      <th><%= model_class.human_attribute_name('descrição') %></th>
      <th><%= model_class.human_attribute_name('vencto') %></th>
      <th><%= model_class.human_attribute_name('pagto') %></th>
      <th><%= model_class.human_attribute_name('parcelas') %></th>
      <th><%= model_class.human_attribute_name('valor R$') %></th>
      <th><%= model_class.human_attribute_name('status') %></th>
      
      
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        
        <td><%= payment.doc_number %></td>
        <td><%= payment.type_doc %></td>
        <td><%= payment.supplier.name %></td>
        <td><%= payment.description %></td>
        <td><%= payment.due_date %></td>
        <td><%= payment.payment_date %></td>
        <td><%= payment.installments %></td>
        <td><%= number_with_precision(payment.value_doc, precision: 2) %></td>
        <td><%= payment.status %></td>
               
        
      </tr>
    <% end %>
  </tbody>
</table>

Total R$: <b><%= @total_payments %></b>
</div>

app/views/payments/show.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1>Conta á Pagar</h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name('Nº docto') %>:</strong></dt>
  <dd><%= @payment.doc_number %></dd>
  <dt><strong><%= model_class.human_attribute_name('fornecedor') %>:</strong></dt>
  <dd><%= @payment.supplier.name %></dd>
  <dt><strong><%= model_class.human_attribute_name('descrição') %>:</strong></dt>
  <dd><%= @payment.description %></dd>
  <dt><strong><%= model_class.human_attribute_name('vencto') %>:</strong></dt>
  <dd><%=l @payment.due_date %></dd>
  <dt><strong><%= model_class.human_attribute_name('pagto') %>:</strong></dt>
  <dd><%=l @payment.payment_date %></dd>
  <dt><strong><%= model_class.human_attribute_name('parcelas') %>:</strong></dt>
  <dd><%= @payment.installments %></dd>
  <dt><strong><%= model_class.human_attribute_name('valor R$') %>:</strong></dt>
  <dd><%= number_with_precision(@payment.value_doc, precision: 2) %></dd>
  <dt><strong><%= model_class.human_attribute_name('tipo docto') %>:</strong></dt>
  <dd><%= @payment.type_doc %></dd>
  <dt><strong><%= model_class.human_attribute_name('forma pagto') %>:</strong></dt>
  <dd><%= @payment.form_payment %></dd>
  <dt><strong><%= model_class.human_attribute_name('status') %>:</strong></dt>
  <dd><%= @payment.status %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              payments_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_payment_path(@payment), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              payment_path(@payment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>