config/routes.rb
Rails.application.routes.draw do

  resources :destinatarios do
  #para autocompletar o fone do cliente na venda
  get :autocomplete_destinatario_celular, :on => :collection
  end
  #abrindo um form modal para cadastrar novos clientes na venda delivery
  get 'desk_orders/new_cliente' => 'desk_orders#new_cliente', :as => :new_cliente

  resources :configs
  resources :form_payments
  #Para o action cable
  mount ActionCable.server => '/cable'

  #ROTAS DO APLICATIVO
  #verifica se a mesa esta liberada
  post 'check_mesa', to: 'desk_orders#check_mesa'
  #lista as categorias dos produtos no cardápio
  get 'list_categories', to: 'desk_orders#list_categories'
  #lista os produtos de acordo com a categoria selecionada
  post 'list_products', to: 'desk_orders#list_products'
  #adiciona o produto selecionado na mesa que está aberta
  post 'add_product', to: 'desk_orders#add_product'
  #exibe tudo o que já foi consumido
  post 'check_order', to: 'desk_orders#check_order'
  #solicita o fechamento da mesa
  post 'close_order', to: 'desk_orders#close_order'
  #exclui o item selecionado se ainda não mudou o status
  post 'delete_item', to: 'desk_orders#delete_item'
  #----------------------------------------------------

  #abrindo um form modal para informar os tributos do pruduto na invoice
  get 'items/editar_tributo' => 'items#editar_tributo', :as => :editar_tributo

  resources :payments
  resources :loginfos
  resources :suppliers do
  #para autocompletar o nome do produto
  get :autocomplete_supplier_name, :on => :collection
  end
  resources :receipts
  resources :qrpoints
  resources :items
  resources :desk_orders do
    member do
     post 'baixar'
     post 'nfce'
     get 'gerar_nfce'

  end
    resources :items do
    end
  end
    resources :items
    post 'barcode', to: 'desk_orders#barcode'
  #para cancelar a nfe
  get 'cancelar_nfe', to: 'desk_orders#cancelar_nfe'
  #para efetivar o cancelamento da nfe
  post 'cancel_nfe', to: 'desk_orders#cancel_nfe'

  resources :products do
    #para autocompletar o nome do produto
   get :autocomplete_product_name, :on => :collection
   #para autocompletar com o codigo de barras lidos
   get :autocomplete_product_barcode, :on => :collection
  end
  #rota para consultar produto selecionado no combobox na Ordem de serviço
  get 'consulta_prod', to: 'products#consulta_prod'
  get 'consulta_prod_barcode', to: 'products#consulta_prod_barcode'


  resources :categories
  get 'pages/login'

  resources :users
  root 'pages#login'

  get 'sessions/new'
  #rotas para o login
  get 'expired', to: 'sessions#expired_date'
  get 'pages/index'
  get 'login', to: 'sessions#new'
  delete 'logout', to: 'sessions#destroy'
  post 'login', to: 'sessions#create'
  #---------------------------------------------
  get 'dashboard', to: 'pages#dashboard'
  #para carregar a view informando que não pode excluir cadastro com relacionamento em outra table
  get 'message_error_relation_tables', to: 'pages#message_error_relation_tables'
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :product
  belongs_to :desk_order
  #quando usar um parametro que não existe no banco de dados, é preciso usar o atributo attr_accessor
  attr_accessor :apply_all, :pizza1, :pizza2
  #para salvar o nome do produto quando é feito uma adição de produto na mesa pelo balcão e naõ pelo produto
  before_create :insert_product_name, :if => lambda { |item| item.name_prod.nil? }
  def insert_product_name
      self.name_prod = self.product.name
      self.local_print = self.product.local_print
      if self.desk_order.destinatario_id.blank? && self.desk_order.status != 'Consumidor'
      self.qrpoint_name = self.desk_order.qrpoint.description
    end
  end
  #action criadas para fazer a baixa dos produtos no estoque e voltar os produtos quando for feito uma exclusão
  after_create :remove_from_stock
  after_destroy :return_to_stock

  #faz a baixa do produto
  def remove_from_stock
    if self.product_id != 0
      @product = Product.find_by_id(product_id)
      if @product.check_stock == !false
      product.qnt -= self.qnt
      product.save
      end
    end
  end
  #retorna o produto para o estoque quando acontece uma exclusão
  def return_to_stock
    if self.product_id != 0
      @product = Product.find_by_id(product_id)
      if @product.check_stock == !false
      product.qnt += self.qnt
      product.save
      end
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :must_login

    #form modal para editar tributos
    def editar_tributo
    @item = Item.find_by(id: params[:id])
    @produto = Product.find_by(id: @item.product_id)
    @cfops = Cfop.order(:codigo)
    respond_to do |format|
    format.html
    format.js
    end
  end

  #para autocompletar o nome do produto
  autocomplete :product, :name
  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @desk_order = DeskOrder.find(params[:desk_order_id])
    if item_params[:product_id].blank?
       sweetalert_warning('Selecione o produto que deseja adicionar!', 'Atenção!', useRejections: false)
       redirect_to desk_order_path(@desk_order) and return
     end
   #verifica se no campo do valor unitário foi digitado incorretamente
    if item_params[:val_unit].to_s == 'NaN'
       sweetalert_warning('O valor unitário do produto foi informado incorretamente, verifique os dados!', 'Atenção!', useRejections: false)
       redirect_to desk_order_path(@desk_order) and return
     end

       if item_params[:qnt].blank?
         sweetalert_warning('Informe uma quantidade para o produto!', 'Atenção!', useRejections: false)
      redirect_to desk_order_path(@desk_order) and return
      else
       @item = @desk_order.items.create(item_params)
         total_itens_atualizado = Item.where(desk_order_id: params[:desk_order_id]).sum(:val_total)
         DeskOrder.update(@desk_order.id, total: total_itens_atualizado.to_f)
       redirect_to desk_order_path(@desk_order)
      end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item = Item.find(params[:id])
    @desk_order = DeskOrder.find(@item.desk_order_id)

    if item_params[:codigo_ncm].blank?
      sweetalert_warning('O campo NCM do item: ' + @item.product.name.to_s + ' não pode ficar em branco, informe o Código com 8 digitos caso queira emitir um documento fiscal posteriormente!', 'Atenção', persistent: 'OK')
    end
    #quando é marcado para aplicar os impostos de uma só vez em todos os itens da venda
    if item_params[:apply_all] == '1'
         Item.where('desk_order_id = ?', @item.desk_order_id).update_all(cfop: item_params[:cfop], icms_situacao_tributaria: item_params[:icms_situacao_tributaria])
         redirect_to desk_order_path(@desk_order) and return
    end
    if @item.update(item_params)
       @item = @desk_order.items.find(params[:id])
     redirect_to desk_order_path(@desk_order)
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy

    @desk_order = DeskOrder.find(params[:desk_order_id])
    @item = @desk_order.items.find(params[:id])
    @item.destroy

    sum_items = Item.where(desk_order_id: params[:desk_order_id].to_i).sum(:val_total)
    DeskOrder.update(params[:desk_order_id].to_i, total: sum_items.to_f)
    redirect_to desk_order_path(@desk_order)
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:product_id, :desk_order_id, :qnt, :val_unit, :val_total, :status, :name_prod, :status, :qrpoint_name, :local_print, :cfop, :codigo_ncm, :icms_situacao_tributaria, :apply_all, :pizza1, :pizza2)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_editar_tributo.html.erb
<script>
	$("#ncm").mask("99999999",{placeholder:""});
	$("#cfop").mask("9999",{placeholder:""});
</script>

<!-- Modal -->
<div data-toggle="modal" data-target="myModal" >
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Informação de tributos <%= image_tag('taxes.png') %></h4>
      </div>
      <div class="modal-body">


<h5><font color="red"><%= @produto.name %></font></h5>
<hr />

<%= form_for @item, :html => { :class => "form-horizontal invoice" } do |f| %>

    <%= f.hidden_field :id, :value=> @item.id %>

    <div class="form-group">
    <%= f.label 'CFOP', :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
    <%= f.collection_select(:cfop, @cfops, :codigo, :codigo, {include_blank: 'Selecione:'},:class => 'form-control', id: 'cfop') %>
    </div>
    </div>

    <div class="form-group">
    <%= f.label 'NCM', :class => 'control-label col-lg-2' %>
    <div class="col-lg-4">
    <%= f.text_field :codigo_ncm, :class => 'form-control', id: 'ncm' %>
    </div>
    </div>

	<div class="form-group">
    <%= f.label 'ICMS:', :class => 'control-label col-lg-2' %>
    <div class="col-lg-5">
    <%= f.select(:icms_situacao_tributaria, options_for_select([["00: tributada integralmente","00"],["10: tributada e com cobrança do ICMS por substituição tributária","10"],["20: tributada com redução de base de cálculo","20"],["30: isenta ou não tributada e com cobrança do ICMS por substituição tributária","30"],["40: isenta","40"],["41: não tributada","41"],["50: suspensão","50"],["51: diferimento (a exigência do preenchimento das informações do ICMS diferido fica a critério de cada UF)","51"],["60: cobrado anteriormente por substituição tributária","60"],["70: tributada com redução de base de cálculo e com cobrança do ICMS por substituição tributária","70"],["90: outras (regime Normal)","90"],["101: tributada pelo Simples Nacional com permissão de crédito","101"],["102: tributada pelo Simples Nacional sem permissão de crédito","102"],["103: isenção do ICMS no Simples Nacional para faixa de receita bruta","103"],["201: tributada pelo Simples Nacional com permissão de crédito e com cobrança do ICMS por substituição tributária","201"],["202: tributada pelo Simples Nacional sem permissão de crédito e com cobrança do ICMS por substituição tributária","202"],["203: isenção do ICMS nos Simples Nacional para faixa de receita bruta e com cobrança do ICMS por substituição tributária","203"],["300: imune","300"],["400: não tributada pelo Simples Nacional","400"],["500: ICMS cobrado anteriormente por substituição tributária (substituído) ou por antecipação"],["900: outras (regime Simples Nacional)","900"]], @item.icms_situacao_tributaria), {include_blank: 'Selecione'}, :class => 'form-control') %>
	</div>
    </div>
    <!--
    <div class="form-group">
    <%= f.label 'IPI:', :class => 'control-label col-lg-2' %>
    <div class="col-lg-3">
    <%= f.select(:ipi_situacao_tributaria, options_for_select([["00: entrada com recuperação de crédito","00"],["01: entrada tributada com alíquota zero","01"],["02: entrada isenta","02"],["03: entrada não-tributada","03"],["04: entrada imune","04"],["05: entrada com suspensão","05"],["49: outras entradas","49"],["50: saída tributada","50"],["51: saída tributada com alíquota zero","51"],["52: saída isenta","52"],["53: saída não-tributada","53"],["54: saída imune","54"],["55: saída com suspensão","56"],["99: outras saídas","99"]], @item.ipi_situacao_tributaria), {include_blank: 'Selecione'}, :class => 'form-control') %>
	</div>
    </div>
    -->

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= f.check_box :apply_all %>&nbsp;<%= f.label "Aplicar á todos itens" %>


<div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit 'Salvar', :class => 'btn btn-primary' %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    </div>
  </div>

<% end %>

app/views/items/_form.html.erb
<!-- Dá o foco no campo para que seja feita a busca com o autocompletar -->
<%if @desk_order.tipo_venda.present? %>
<script>
$(document).ready(function(){
$('#codigo-barra').focus();
});
</script>
<% else  %>
<script>
$(document).ready(function(){
$('#id_do_produto').focus();
});
</script>
<% end %>

<script>
// AQUI É FEITA A CONSULTA COM BASE NO PRODUTO SELECIONADO NO COMBOBOX E EXIBIDO NOS TEXTFIELDS O RESULTADO
$(document).ready(function() {
    $("#codigo-barra").on("focusout", function(){
  	// limpa os campos primeiro
  	$("#qnt").val('1');
    $("#val_unit").val('');
  	$("#total_geral").val('');
    	$.ajax({
    		url: '/consulta_prod_barcode.json',
    		data: {
    			name: $( "#codigo-barra" ).val(),
    		},
    		datatype: "script",
    		success: function(obj){
          $('#id-do-prod').val(obj.id);
        	$('#qnt').val('1');
        	$('#val_unit').val(obj.value);
               var total = $('#qnt').val() * $('#val_unit').val();
               $('#total_geral').val(total.toFixed(2));
        },
        error: function(){
            console.log(arguments);
        }
    	});
   	});

    // AQUI É FEITA A CONSULTA COM BASE NO PRODUTO SELECIONADO NO TEXTFIELD E EXIBIDO NOS TEXTFIELDS O RESULTADO
    $("#id_do_produto").focusout(function() {
  	// limpa os campos primeiro
    $("#qnt").val('');
  	$("#total_geral").val('');
    	var produto = $('#id_prod').val()

    	$.ajax({
    		url: '/consulta_prod.json',
    		data: {
    			name: produto,
    		},
    		datatype: "script",

    		success: function(obj){

    		$('#id_prod').val(obj.id);
    		$('#descricao_produto').val(obj.descricao);
        $('#ncm').val(obj.codigo_ncm);
				$('#val_unit').val(parseFloat(obj.value).toFixed(2));

        },
        error: function(){
            console.log(arguments);
        }

    	});
   	});
 });

</script>

<script>
$(document).ready(function(){
$('#qnt').on('keyup',function(){
     var total = $('#qnt').val() * $('#val_unit').val();
     $('#total_geral').val(total.toFixed(2));
});

  $("#qnt").on('focusout',function(){
  $(".botao").focus()
  });
});
</script>

<!-- chama o modal para montar as pizzas -->
<script>
$(document).ready(function(){
  $('#id_do_produto').on('focusout',function(){
    if ($('#id_do_produto').val() == "pz"){
  $('#Modal-pizza').modal('show');
}
});

$('#Modal-pizza').on('hidden.bs.modal', function (e) {
  $('#id_do_produto').focus();
});
});
</script>


<h5><b>Adicionar produtos:</b></h5>
<%= form_for ([@desk_order, @desk_order.items.build]) do |f| %>

<% if @desk_order.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@desk_order.errors.count, "error") %> prohibited this heritage from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @desk_order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <%= f.hidden_field :codigo_ncm, id: 'ncm' -%>
<% if @desk_order.tipo_venda.present? %>
<div class="col-lg-2">
<%= f.text_field :product_id, :class => 'form-control',placeholder: 'Código de barras:', id: 'codigo-barra' %>
<%= f.hidden_field :product_id, id: 'id-do-prod' %>
</div>
  <% else %>
	<div class="col-lg-2">
	<%= f.autocomplete_field :product_id, autocomplete_product_name_products_path, :id_element => '#id_prod', :class => 'form-control',placeholder: 'Digite o nome do produto:', id: 'id_do_produto' %>
	<%= f.hidden_field :product_id, id: 'id_prod' %>
	</div>
<% end %>

    <div class="col-lg-1">
	<%= f.text_field :qnt, class: "form-control", placeholder: "qnt", id: 'qnt' -%>
	</div>

	<!-- SE FOR PRECISO ALTERAR O VALOR DE VENDA UNITÁRIO DO PRODUTO NA HORA DA VENDA -->
	<div class="col-lg-1">
	<%= f.text_field :val_unit, class: "form-control", id: 'val_unit', placeholder: 'Valor unit R$' -%>
	</div>

	<div class="col-lg-1">
	<%= f.text_field :val_total, class: "form-control", placeholder: "Total R$", id: 'total_geral', readonly: true -%>
	</div>

  <%= f.submit 'Adicionar', class: 'botao btn-primary btn-lg', id: 'add' %>
<% end %>

app/views/items/_item.html.erb
<hr />
<table class="table table-striped">
  <thead>
    <tr>
      <th> <%= 'Produto' %></th>
      <th><%= 'Qnt' %></th>
      <th><%= 'Valor unit' %></th>
      <th><%= 'Total' %></th>
      <th><%= 'Imagem' %></th>
      <% if @desk_order.status == 'Aberta' || @desk_order.status == 'Em uso' %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>

    </tr>
  </thead>
  <tbody>

 	<% @desk_order.items.order(:created_at).each do |item| %>
        <tr>
        <td><%= item.name_prod %></td>
        <td><%= item.qnt %></td>
        <td>R$ <%= number_with_precision(item.val_unit, precision: 2) %></td>
        <td>R$ <%= number_with_precision(item.val_total, precision: 2) %></td>
        <% if item.product.image.present? %>
	        <td><%= image_tag(item.product.image.url, :size => "25x25", class: "css-style") %></td>
	      <% else %>
	        <td>Sem imagem</td>
	      <% end %>
        <td><%= link_to 'Informar tributos', editar_tributo_path(:id => item.id), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal', :class => 'btn btn-xs btn-default'}  %></td>
        <% if @desk_order.status == 'Aberta' || @desk_order.status == 'Em uso' || @desk_order.status.blank? %>
          <td><%= link_to t('.destroy', :default => t("helpers.links.destroy")), [item.desk_order, item], :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger' %></td>
        <% end %>
       </tr>
      <% end %>
       </tbody>
   </table>

app/views/items/_pizza.html.erb
<script>
$(document).ready(function(){
  $("#quantidade").on('focusout',function(){
  $(".btn").focus()
  });

$('#quantidade').on('keyup',function(){
     var total = $('#quantidade').val() * $('#val_unitario').val();
     $('#valor_geral').val(total.toFixed(2));
});
// AQUI É FEITA A CONSULTA COM BASE NO PRODUTO SELECIONADO NA PIZZA 1
      $("#pizza1").change(function(){
  	// limpa os campos primeiro
    $("#quantidade").val('');
  	$("#valor_geral").val('');
    	var produto = $('#pizza1').val();
    	$.ajax({
    		url: '/consulta_prod.json',
    		data: {
    			name: produto,
    		},
    		datatype: "script",
    		success: function(obj){
    		$('#id_prod').val(obj.id);
    		window.pizza_1 = obj.name;
        window.valor_pizza1 = obj.value;
        window.id_produto1 = obj.id;
        $('#codigo_produto').val(window.id_produto1);
        //$('#quantidade').val(obj.qnt);
        $('#valor_ncm').val(obj.codigo_ncm);
			//AQUI É ONDE MOSTRA O VALOR COM .00 AO TRAZER O VALOR DE VENDA DO PRODUTO
			$('#val_unitario').val(parseFloat(obj.value).toFixed(2));
      $('#pizza').val(window.pizza_1);
      $("#pizza2").val('');
      $('#pizza2').focus();
          },
        error: function(){
            console.log(arguments);
        }
    	});
   	});
    // AQUI É FEITA A CONSULTA COM BASE NO PRODUTO SELECIONADO NA PIZZA 2
          $("#pizza2").change(function(){
      	// limpa os campos primeiro
        $("#quantidade").val('');
      	$("#valor_geral").val('');
        	var produto = $('#pizza2').val();
        	$.ajax({
        		url: '/consulta_prod.json',
        		data: {
        			name: produto,
        		},
        		datatype: "script",
        		success: function(obj){
        		$('#id_prod').val(obj.id);
            $('#valor_ncm').val(obj.codigo_ncm);
        		window.pizza_2 = obj.name;
            window.valor_pizza2 = obj.value;
            window.id_produto2 = obj.id;
            //verifica qual pizza é a mais cara
            if(window.valor_pizza1 > window.valor_pizza2) {
              $('#val_unitario').val(parseFloat(window.valor_pizza1).toFixed(2));
              $('#codigo_produto').val(window.id_produto1);
            } else {
              $('#val_unitario').val(parseFloat(window.valor_pizza2).toFixed(2));
              $('#codigo_produto').val(window.id_produto2);
            }

          // verifica se é meio a meio a pizza para concatenar o nome
          if ( $('#pizza2').val() != 'Selecione:' ) {
            var nome_pizza = '1/2 ' + window.pizza_1 + ' 1/2 ' + window.pizza_2;
            $('#pizza').val(nome_pizza);
          }
          $('#quantidade').focus();
            },
            error: function(){
                console.log(arguments);
            }
        	});

       	});
    });
</script>

<!-- chama o modal para montar as pizzas -->
<script>
$(document).ready(function(){
  $('#Modal-pizza').on('hidden.bs.modal', function (e) {
    $('#id_do_produto').focus();
  });
});
</script>

<h5><b>Selecione ou monte suas Pizzas:</b></h5>
<%= form_for ([@desk_order, @desk_order.items.build]) do |f| %>

<% if @desk_order.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@desk_order.errors.count, "error") %> prohibited this heritage from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @desk_order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <%= f.hidden_field :codigo_ncm, id: 'valor_ncm' %>
  <%= f.hidden_field :product_id, id: 'codigo_produto' %>

  <div class="form-group">
      <%= f.label 'Pizza 1', :class => 'control-label col-lg-2' %>
      <div class="col-lg-8">
        <%= f.collection_select(:pizza1, @products, :id, :name, {include_blank: 'Selecione:'}, :class => 'form-control', id: 'pizza1') %>
      </div>
      <%=f.error_span(:pizza1) %>
  </div>
<br>
<p>
<br>
  <div class="form-group">
      <%= f.label 'Pizza 2', :class => 'control-label col-lg-2' %>
      <div class="col-lg-8">
        <%= f.collection_select(:pizza2, @products, :id, :name, {include_blank: 'Selecione:'}, :class => 'form-control',id: 'pizza2') %>
      </div>
      <%=f.error_span(:pizza2) %>
  </div>
<br>
<p>
<br>
<div class="col-lg-10">
<%= f.text_field :name_prod, class: "form-control", placeholder: "nome da pizza", id: 'pizza', readonly: true %>
</div>
<br>
<p>
<br>
<div class="col-lg-2">
<%= f.text_field :qnt, class: "form-control", placeholder: "qnt", id: 'quantidade' -%>
</div>

<!-- SE FOR PRECISO ALTERAR O VALOR DE VENDA UNITÁRIO DO PRODUTO NA HORA DA VENDA -->
<div class="col-lg-3">
<%= f.text_field :val_unit, class: "form-control", id: 'val_unitario', placeholder: 'Val. unit R$', readonly: true -%>
</div>

<div class="col-lg-3">
<%= f.text_field :val_total, class: "form-control", placeholder: "Total R$", id: 'valor_geral', readonly: true -%>
</div>

  <%= f.submit 'Adicionar', class: 'btn btn-success', id: 'add' %>
<% end %>

app/views/items/edit.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/editar_tributo.js.erb
$("#myModal").html("<%= escape_javascript(render 'items/editar_tributo') %>");
$("#myModal").modal();

app/views/items/index.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:product_id) %></th>
      <th><%= model_class.human_attribute_name(:desk_order_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.id, item_path(item) %></td>
        <td><%= item.product_id %></td>
        <td><%= item.desk_order_id %></td>
        <td><%=l item.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      item_path(item), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_item_path(item), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_path(item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_item_path,
            :class => 'btn btn-primary' %>

app/views/items/new.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:product_id) %>:</strong></dt>
  <dd><%= @item.product_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:desk_order_id) %>:</strong></dt>
  <dd><%= @item.desk_order_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>